const fs = require('node:fs');
const path = require('node:path');
const { createHash } = require('node:crypto');
const { publicEntries } = require('../src/host/installation.cjs');
const root = path.join(__dirname, '..');
const output = path.join(root, 'build/plugin');

function generatedFiles(directory = root) {
  const pkg = JSON.parse(fs.readFileSync(path.join(directory, 'package.json')));
  const nativeSource = [
    'shared/core.js',
    'figma/design-queries.js',
    'figma/script-runtime.js',
    'figma/native-runtime.js',
  ]
    .map((name) => fs.readFileSync(path.join(directory, 'src', name), 'utf8'))
    .join('\n');
  // A skill or workbench release must not restart an unchanged native kernel.
  // Its identity follows actual code bytes, independent of package metadata.
  const code =
    '// Generated by npm run build. Edit src/ files.\n' +
    'const FIGMA_PLUGIN_BUILD = ' +
    JSON.stringify(createHash('sha256').update(nativeSource).digest('hex')) +
    ';\n' +
    nativeSource;
  const template = fs.readFileSync(
    path.join(directory, 'src/figma/ui.template.html'),
    'utf8',
  );
  if (template.split('<!-- BRIDGE_SCRIPT -->').length !== 2)
    throw new Error('UI must contain one build insertion point');
  if (template.split('/* CODEX_STYLES */').length !== 2)
    throw new Error('UI must contain one shared style insertion point');
  const ui = template
    .replace('/* CODEX_STYLES */', () =>
      fs.readFileSync(path.join(directory, 'src/shared/codex.css'), 'utf8'),
    )
    .replace(
      '<!-- BRIDGE_SCRIPT -->',
      () =>
        '<script>\n' +
        fs.readFileSync(path.join(directory, 'src/figma/ui.js'), 'utf8') +
        '\n</script>',
    );
  const metadata = JSON.parse(
    fs.readFileSync(path.join(directory, 'plugin.json')),
  );
  const presentation = metadata.extensions['com.openai'].interface;
  const iconSource = presentation.composerIcon;
  if (presentation.logo !== iconSource)
    throw new Error('Plugin branding must share one SVG source');
  const icon = fs.readFileSync(path.join(directory, iconSource));
  const iconPath = iconSource.replace(
    /\.svg$/,
    '-' + createHash('sha256').update(icon).digest('hex') + '.svg',
  );
  presentation.composerIcon = presentation.logo = iconPath;
  return {
    'plugin.json':
      JSON.stringify({ ...metadata, version: pkg.version }, null, 2) + '\n',
    [iconPath.slice(2)]: icon,
    'plugin-runtime.js': code,
    'ui.html': ui,
    ...require('./build-app.cjs').buildApp(directory),
  };
}
function build(check = false) {
  const generated = generatedFiles(),
    pkg = require('../package.json');
  const iconSource =
    require('../plugin.json').extensions[
      'com.openai'
    ].interface.composerIcon.slice(2);
  const inputs = publicEntries(
    root,
    pkg.distributionFiles.filter((file) => !Object.hasOwn(generated, file)),
  ).filter((file) => file !== iconSource);
  const contents = {
    ...generated,
    ...Object.fromEntries(
      inputs.map((file) => [file, fs.readFileSync(path.join(root, file))]),
    ),
  };
  if (!check) fs.rmSync(output, { recursive: true, force: true });
  for (const [file, content] of Object.entries(contents)) {
    const destination = path.join(output, file),
      bytes = Buffer.from(content);
    if (check) {
      if (
        !fs.existsSync(destination) ||
        !fs.readFileSync(destination).equals(bytes)
      )
        throw new Error(`${file} is stale; run npm run build`);
    } else {
      fs.mkdirSync(path.dirname(destination), { recursive: true });
      fs.writeFileSync(destination, bytes);
    }
  }
  if (
    check &&
    JSON.stringify(publicEntries(output)) !==
      JSON.stringify(Object.keys(contents).sort())
  )
    throw new Error('Build file list is stale');
  return output;
}
if (require.main === module) build(process.argv.includes('--check'));
module.exports = { build, generatedFiles, output };
